---
root: true

globals:
  IS_DEVELOPMENT: "readonly"

env:
  browser: true
  commonjs: true
  es2021: true

extends:
  - airbnb

parserOptions:
  ecmaVersion: 2019

rules:
  newline-before-return: "error"
  no-console: "off"
  semi: ["error", "never"]
  react/prop-types: "off"
  quotes: ["error", "double"]
  react/react-in-jsx-scope: "off"
  react/jsx-props-no-spreading: "off"

overrides:
  - files: ["*.js", "*.jsx"]
    rules:
      comma-dangle: ["error", "never"]
